tiltft:
  riot-api-key: ${RIOT_API_KEY}

spring:
  data:
    rest:
      base-path: /api

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds